// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockerDB.Data.Stocker
{
    public partial class LenovoDevices
    {
        public int Id { get; set; }
        public DateTime LastUpdated { get; set; }
        public string ProductID { get; set; }
        public string Name { get; set; }
        public string ProductURL { get; set; }
        public string ImageURL { get; set; }
        public string ProductGUID { get; set; }
        public string ParentGUID { get; set; }
        public string FullGUID { get; set; }
    }
}