// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockerDB.Data.Stocker
{
    public partial class PartsStock
    {
        public int Id { get; set; }
        public DateTime LastUpdated { get; set; }
        public string Warehouse { get; set; }
        public string PartNumber { get; set; }
        public decimal? Price_NL { get; set; }
        public int? Stock_NL { get; set; }
        public decimal? Price_UK { get; set; }
        public int? Stock_UK { get; set; }
        public decimal? Price_CH { get; set; }
        public int? Stock_CH { get; set; }
        public decimal? Price_DK { get; set; }
        public int? Stock_DK { get; set; }
        public DateTime? Date_Incoming_NL { get; set; }
        public DateTime? Date_Incoming_UK { get; set; }
        public DateTime? Date_Incoming_CH { get; set; }
        public DateTime? Date_Incoming_DK { get; set; }
    }
}