// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockerDB.Data.Stocker
{
    public partial class WarehouseConnections
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string ConnectionUri { get; set; }
        public string LoginName { get; set; }
        public string LoginSecret { get; set; }
        public DateTime? LastUpdated { get; set; }
    }
}