// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockerDB.Data.Stocker
{
    public partial class WarehouseProducts_ALSO
    {
        public int Id { get; set; }
        public DateTime? LastUpdated { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public byte? CarePack { get; set; }
        public string Warranty { get; set; }
        public int? Stock_EE { get; set; }
        public decimal? Price_EE { get; set; }
        public int? Stock_FI { get; set; }
        public decimal? Price_FI { get; set; }
        public int? Stock_LV { get; set; }
        public decimal? Price_LV { get; set; }
        public int? Stock_LT { get; set; }
        public decimal? Price_LT { get; set; }
        public DateTime? BidValidFrom { get; set; }
        public DateTime? BidValidTill { get; set; }
        public int? BidMaxQty { get; set; }
        public int? BidFreeQty { get; set; }
        public decimal? BidPrice { get; set; }
        public string BidEndUser { get; set; }
    }
}