// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockerDB.Data.Stocker
{
    public partial class WarehouseProducts
    {
        public int Id { get; set; }
        public DateTime LastUpdated { get; set; }
        public string Warehouse { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public byte? CarePack { get; set; }
        public string Warranty { get; set; }
        public int? Stock_Local { get; set; }
        public int? Stock_Remote { get; set; }
        public decimal? Price_Local { get; set; }
        public decimal? Price_Remote { get; set; }
        public int? Stock_Incoming { get; set; }
        public DateTime? Date_Incoming { get; set; }
        public int? Stock_Reserved { get; set; }
        public int? Stock_Ordered { get; set; }
        public DateTime? BidValidFrom { get; set; }
        public DateTime? BidValidTill { get; set; }
        public int? BidMaxQty { get; set; }
        public int? BidFreeQty { get; set; }
        public decimal? BidPrice { get; set; }
        public string BidEndUser { get; set; }
    }
}