### stock status is available from (action)cc_lenovo_ctrl_ProductListShowProduct => (method)InventoryBy_Warehouse
POST https://www.lenovopartsales.com/LenovoEsales/apexremote HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Content-Type: application/json
Referer: https://www.lenovopartsales.com/LenovoEsales/ccrz__Products?cartID=&portalUser=&store=&cclcl=en_US&operation=quickSearch&searchText=t14

{
    "action": "cc_lenovo_ctrl_ProductListShowProduct",
    "method": "InventoryBy_Warehouse",
    "data": [{},["00HM105", "00HM106"]],
    "type": "rpc",
    "tid": 13,
    "ctx": {
        "csrf": "VmpFPSxNakF5TWkwd09DMHlNVlF5TURveU56bzBNeTQwTXpkYSw5NVNJWDZTTEpKemxYWTA1UWxoLW5iLE1HTXpNVE15",
        "vid": "066a0000000CqD0",
        "ns": "",
        "ver": 41
    }
}


### price is available from (action)crz.cc_ctrl_ProductListRD => (method)fetchPage
POST https://www.lenovopartsales.com/LenovoEsales/apexremote HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Content-Type: application/json
Referer: https://www.lenovopartsales.com/LenovoEsales/ccrz__Products?cartID=&portalUser=&store=&cclcl=en_US&operation=quickSearch&searchText=t14

{
    "action": "ccrz.cc_ctrl_ProductListRD",
    "method": "fetchPage",
    "data": [{},
        [
            {
                "sku": "00HM105"
            },
            {
                "sku": "00HM106"
            }
        ]
    ],
    "type": "rpc",
    "tid": 10,
    "ctx": {
        "csrf": "VmpFPSxNakF5TWkwd09DMHlNVlF5TURveU56bzBNeTQwTkRKYSxQSWtZa19nbGVqTGlNdHBoVGh6aTRnLE5HRTJNamcz",
        "vid": "066a0000000CqD0",
        "ns": "ccrz",
        "ver": 50
    }
}